### ISSUE TITLE
project permission error with bigquery.py

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#13]
The README needs to mention where to get the project id and where to set it in bigquery.py otherwise you'll get 403 and have to research.

This error (w/ booming-flash or whatever is hard-coded) would be good in a troubleshooting section: 
google.api_core.exceptions.Forbidden: 403 POST https://www.googleapis.com/bigquery/v2/projects/booming-flash-176918/jobs: Access Denied: Project booming-flash-176918: The user xxx@gmail.com does not have bigquery.jobs.create permission in project booming-flash-176918.

**Comment by tonanhngo** [comment]
Good point, let me change that hard-coded project id to something like "change-to-your-project-id"
