### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#18]
The instructions to install requirements seem to be missing.  I think I followed the README and I got this error running convert.py:

$ python3 convert.py --dataset_dir="~/tfd"
Traceback (most recent call last):
  File "convert.py", line 35, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by tonanhngo** [comment]
Added instruction to install TensorFlow on workstation as prerequisite
