### ISSUE TITLE
CONTRIBUTING.md has placeholders

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#2]
The setup, testing and style guidelines should be customized for this project (or removed if n/a)

**Comment by tonanhngo** [comment]
We missed these, thanks for pointing them out.
I added content for the setup and testing, and removed the style guideline

**Comment by markstur** [comment]
We almost always miss these, I think.  I just got caught on that, so I'm paying it forward.
 
----- Original message -----From: Ton Ngo <notifications@github.com>To: IBM/tensorflow-kubernetes-art-classification <tensorflow-kubernetes-art-classification@noreply.github.com>Cc: Mark Sturdevant <mark.sturdevant@ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBM/tensorflow-kubernetes-art-classification] CONTRIBUTING.md has placeholders (#2)Date: Fri, Nov 3, 2017 10:28 AM 
We missed these, thanks for pointing them out.I added content for the setup and testing, and removed the style guideline

**Comment by markstur** [comment]
fixed
