### ISSUE TITLE
~/data doesn't work on Mac.  Use full path e.g. /Users/yournamehere/data instead

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#26]
Looks like a known issue with the handling of ~/ on MacOS.

Probably could be fixed somewhere by expanding path or at least noted in the README.
For now recording the issue here.

**Comment by tonanhngo** [comment]
It's probably best to use the full path, and name it something obvious as you suggest.

**Comment by winnietsang** [comment]
just merged the above pull request for this issue
