### ISSUE TITLE
Needed /v1 instead of :v1 in the yaml image names

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#27]
I think I followed the instructions, but the :v1 example did not work for me.  I needed to use /v1 in the image name in the yaml files instead.

Curious if anyone can reproduce this.

**Comment by winnietsang** [comment]
In the README the image is met-art:v1(image name = "met-art" and tag = "v1"). I didn't need to change ":" to "/". May you give me more info on how to reproduce the problem you experience. @markstur  may you please check does your image name have a "/" on it by the following command
bx cr image-list

**Comment by markstur** [comment]
looks like I accidentally used /v1 instead of :v1 in my docker tag destination.  So it became part of the name.  Closing.
