### ISSUE TITLE
trained model link in box is not accessible

### ISSUE THREAD

**Issue by hjjo** [IBM/tensorflow-kubernetes-art-classification#32]
https://ibm.box.com/s/wyzl1k2tz1nosrf44mj20cmlruy7gsut

**Comment by stevemar** [comment]
cc @tonanhngo -- can you address the above?

**Comment by hjjo** [comment]
I want to use this code pattern in the workshop on next Monday.
Two problems should be solved before the workshop.
The first problem is addressed in this issue, and the second problem is that when I try to classify an image (which image is in met_art), trained model returns NONE even if it was used for training. Actually I see every result as NONE.. Is this problem should be solved if I use your trained model? (which was trained with more images) Or did I something wrong?

**Comment by tonanhngo** [comment]
@hjjo, I went to the box note but it says "This shared file or folder link has been removed or is unavailable to you."  Maybe you need to set the access permission?  
The problem with "NONE" result is likely because the file that lists the categories is not visible or accessible.

**Comment by hjjo** [comment]
@tonanhngo The link is provided by this repository README.md and I want to get this file but not accessible.

**Comment by tonanhngo** [comment]
@hjjo, ah got it.  I thought you were sharing something with us.  Yes the checkpoint files are supposed to be there, we will take a look to see what the problem is.

**Comment by winnietsang** [comment]
@hjjo, please try the link again, it should be working now. 
For the "NONE" result I agree with @tonanhngo that is cause by the lists of categories not visible or accessible.

**Comment by hjjo** [comment]
@tonanhngo @winnietsang Thanks I'm able to get the file now. 
And I found that the training process was killed immediately, it was caused by (maybe) out of memory. I solved it with adding an option --batch_size=1 (may be --batch_size=10 also works).
