### ISSUE TITLE
readme text says ~/data/met_art but command example just uses ~/data

### ISSUE THREAD

**Issue by markstur** [IBM/tensorflow-kubernetes-art-classification#9]
I think the text and example are not in sync.  Didn't verify, but it looks wrong.

**Comment by tonanhngo** [comment]
This is actually correct and it's just the convention that the image classification code uses.  The directories and the pictures are placed in "~/data/met_art", where "met_art" is the dataset name.

**Comment by tonanhngo** [comment]
If you think this may be confusing to the users, we can reopen this issue and figure out some other convention.
